[project]
name = "ragdnet"
version = "0.1.0"
description = "RAGDnet"
requires-python = ">=3.10"
authors = [
  { name = "Alexandre MONNIER WEIL" }
]
dependencies = [
    # Processing
    "networkx>=3.3",
    "numpy>=2.1.2",
    "tqdm>=4.66.5",
    "ezdxf>=1.4.0",
    "matplotlib>=3.10.1",
    "scikit-image>=0.25.2",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.2",
    "shapely>=2.1.2",
    "opencv-python>=4.11.0.86",
    # Learning graph
    "torch-geometric>=2.6.1",
    "torch>=2.6.0",
    "scikit-learn>=1.6.1",
    "lightning>=2.5.1",
    "pyg-lib>=0.4.0",
    "checksumdir>=1.3.0",
    # Learning vision
    "albumentations",
    "transformers>=4.57.1",
    "torchvision>=0.21.0",
    # dash board
    "tensorboard>=2.20.0",
    # nvidia dependencies for LINUX
    "nvidia-cublas-cu12==12.6.4.1;    platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cuda-cupti-cu12==12.6.80; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cuda-nvrtc-cu12==12.6.77; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cuda-runtime-cu12==12.6.77; platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cudnn-cu12==9.5.1.17;     platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cufft-cu12==11.3.0.4;     platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-curand-cu12==10.3.7.77;   platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cusolver-cu12==11.7.1.2;  platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cusparse-cu12==12.5.4.2;  platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-cusparselt-cu12==0.6.3;   platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-nccl-cu12==2.21.5;        platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-nvjitlink-cu12==12.6.85;  platform_machine == 'x86_64' and sys_platform == 'linux'",
    "nvidia-nvtx-cu12==12.6.77;       platform_machine == 'x86_64' and sys_platform == 'linux'",
    "triton==3.2.0;                   platform_machine == 'x86_64' and sys_platform == 'linux'",
]

[tool.uv.extra-build-dependencies]
torch-sparse = ["torch"]


[tool.uv.sources]
pyg_lib         = { index = "pyg-lib-flat" }
torch-sparse    = { index = "pyg-lib-flat" }
torch-scatter   = { index = "pyg-lib-flat" }
torch-cluster   = { index = "pyg-lib-flat" }
torch-spline-conv = { index = "pyg-lib-flat" }

torch           = { index = "pytorch-cu126" }
albumentations  = { git = "https://github.com/albu/albumentations.git" }

[[tool.uv.index]]
name   = "pyg-lib-flat"
url    = "https://data.pyg.org/whl/torch-2.6.0+cu126.html"
format = "flat"

[[tool.uv.index]]
name     = "pytorch-cu126"
url      = "https://download.pytorch.org/whl/cu126"
explicit = true

[project.scripts]
xpipe = "ragdnet.pipelines.xpipe:main"
train_gnn = "ragdnet.learning.train.train_gnn:main"
train_vision = "ragdnet.learning.train.train_vision:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[tool.hatch.build.targets.wheel]
packages = ["src/ragdnet"]