[segmenter]
class = "PeakSegment"
[segmenter.params]
angle_range = [75,115]
epsilon_rdp = 2.12
peak_detection = true

[watershed]
class = "DistanceTransformWatershed"

[graph_builder]
class = "RegionGraphKNN"
[graph_builder.params]
k = 5


[labeler]
class = 'RegionLabeler'


