[segmenter]
class = "PeakSegment"
[segmenter.params]
angle_range = [0,0]
epsilon_rdp = 2.12
peak_detection = false

[watershed]
class = "DistanceTransformWatershed"

[graph_builder]
class = "RegionGraphKNN"
[graph_builder.params]
k = 3

[labeler]
class = 'RegionLabeler'


